// Session utility functions for Memory Reconsolidation Wizard

import {
  MemoryReconsolidationSession,
  MemoryReconsolidationDraft,
  IntegrationChoiceType,
  IntegrationSelection,
} from '../../types';
import { GROUNDING_OPTIONS } from '../../constants';

export const createBaseSession = (): MemoryReconsolidationSession => ({
  id: `memrecon-${Date.now()}`,
  date: new Date().toISOString(),
  currentStep: 'ONBOARDING',
  implicitBeliefs: [],
  contradictionInsights: [],
  juxtapositionCycles: [],
  groundingOptions: GROUNDING_OPTIONS,
  integrationSelections: [],
  baselineIntensity: 5,
});

export const hydrateSession = (draft?: MemoryReconsolidationDraft | null): MemoryReconsolidationSession => {
  const base = createBaseSession();
  const baseline = draft?.baselineIntensity ?? base.baselineIntensity;

  return {
    ...base,
    ...draft,
    id: draft?.id ?? base.id,
    date: draft?.date ?? base.date,
    currentStep: draft?.currentStep ?? base.currentStep,
    implicitBeliefs: draft?.implicitBeliefs ?? base.implicitBeliefs,
    contradictionInsights: draft?.contradictionInsights ?? base.contradictionInsights,
    groundingOptions:
      draft?.groundingOptions && draft.groundingOptions.length > 0
        ? draft.groundingOptions
        : base.groundingOptions,
    integrationSelections: draft?.integrationSelections ?? base.integrationSelections,
    baselineIntensity: baseline,
    juxtapositionCycles: (draft?.juxtapositionCycles ?? base.juxtapositionCycles).map((cycle, index) => ({
      ...cycle,
      id: cycle.id || `cycle-${index}`,
      steps: cycle.steps || [],
      intensity: {
        baselineIntensity: cycle.intensity?.baselineIntensity ?? baseline,
        postIntensity: cycle.intensity?.postIntensity,
        shiftPercentage: cycle.intensity?.shiftPercentage,
      },
    })),
  };
};

export const mapUiChoiceToIntegrationType = (choice: 'curated' | 'self-guided'): IntegrationChoiceType =>
  choice === 'curated' ? 'practice-stack' : 'embodied-action';

export const mapIntegrationTypeToUi = (
  choice?: IntegrationChoiceType,
  selections?: IntegrationSelection[],
): 'curated' | 'self-guided' | null => {
  if (selections?.some(sel => sel.practiceId === 'custom-plan')) return 'self-guided';
  if (choice === 'practice-stack') return 'curated';
  if (choice) return 'self-guided';
  if (selections && selections.length > 0) return 'curated';
  return null;
};

export const generateReportContent = (
  session: MemoryReconsolidationSession,
  postIntensity: number | null,
  selectedGrounding: string[],
  schedulingCommitment: string,
): string => {
  const selectedBelief = session.implicitBeliefs[0];
  const shiftPercentage = session.completionSummary?.intensityShift
    ? Math.round((session.completionSummary.intensityShift / session.baselineIntensity) * 100)
    : 0;

  return `# Memory Reconsolidation Session Report
Date: ${new Date(session.date).toLocaleDateString()}

## Memory/Belief Addressed
${selectedBelief?.belief || 'N/A'}

Category: ${selectedBelief?.category || 'N/A'}
Emotional Charge: ${selectedBelief?.emotionalCharge || 'N/A'}/10
Body Location: ${selectedBelief?.bodyLocation || 'N/A'}

## Contradictions Explored
${session.contradictionInsights.map((c, i) => `${i + 1}. ${c.anchors.join(', ')}`).join('\n')}

## Intensity Shift
Baseline: ${session.baselineIntensity}/10
Post-Session: ${postIntensity}/10
Change: ${shiftPercentage}%

## Integration Plan
${session.completionSummary?.selectedPractices.map(p => `- ${p.practiceName}: ${p.rationale}`).join('\n') || 'N/A'}

## Grounding Resources Selected
${selectedGrounding
  .map(id => {
    const grounding = session.groundingOptions.find(g => g.id === id);
    return `- ${grounding?.name}: ${grounding?.description}`;
  })
  .join('\n')}

## Insights & Notes
${session.completionSummary?.userInsights || 'N/A'}

## Scheduling Commitment
${schedulingCommitment}

---
Generated by Aura ILP - Memory Reconsolidation Protocol
`;
};

export const generateSummaryText = (
  selectedBelief: { belief: string } | undefined,
  shiftPercentage: number,
  selectedPractices: string[],
): string => {
  return `Memory Reconsolidation Session Summary

Belief: ${selectedBelief?.belief}
Intensity Shift: ${shiftPercentage}%
Integration: ${selectedPractices.join(', ')}`;
};

export const calculateIntensityShift = (
  postIntensity: number | null,
  baselineIntensity: number,
): number => {
  return postIntensity !== null
    ? Math.round(((postIntensity - baselineIntensity) / baselineIntensity) * -100)
    : 0;
};
